services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-pg
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: web-backend
    ports:
      - "5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql
    command: ["postgres", "-c", "cron.database_name=web-backend"]
volumes:
  pg18_data:
